executable = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_simulation/3_generate_mini-albums.py
arguments = $(sim_num)

log = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_logs/job.log
output = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_logs/stepThree_$(sim_num).$(Cluster).out
error = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_logs/stepThree_$(sim_num).$(Cluster).err
request_cpus = 1
request_memory = 400MB

queue