executable = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_simulation/4_merge_mini-albums.py

log    = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_logs/jobs.log
output = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_logs/step4fin_$(sim_num)_$(Cluster).out
error  = /data/condor_shared/users/ssued/RNOG_Image_Builder/jobs/jobs_logs/step4fin_$(sim_num)_$(Cluster).err
request_cpus = 1
request_memory = 400MB

queue